# Generated by Django 6.0 on 2025-12-15 13:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road', '0003_adminuser_delete_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorityprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
