# Generated by Django 6.0 on 2026-01-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road', '0005_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='admin_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='authorityprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('ROAD', 'road'), ('WATER', 'water')], max_length=5),
        ),
    ]
